Feature/certification page
Ethiopian-Data-Science-Association/edsa-website pull request #11
Opened 2024-11-09 14:15 UTC by brooksideas

## 📝 Summary

> **Why** is this Pull Request necessary? Provide a concise explanation of the change or feature.  
> For example: "Fixes a bug", "Implements a new feature", or "Bumping package version".

## 📝 Summary

This Pull Request introduces the **Certification Management feature**. It implements several pages and functionalities: Create, Edit, Register, Detail, and List certifications. These additions allow users to manage certification details, register for courses, and view certification information, providing a streamlined experience for both users and admins in managing certifications.

## 📊 Impact

> **Scope**: These changes apply primarily to the certification pages and components, including `CertificationList`, `CertificationDetail`, `CertificationCreateForm`, `CertificationEditForm`, and `CertificationRegister`. Each component and page has specific Vue and Vuex store integrations to handle user interactions, data validation, and persistence.

> **Affected parties**: Only users interacting with certification features are impacted. Admins benefit from streamlined create and edit workflows, while general users can view and register for certifications.

> **Risk Assessment**: Minimal risk, as these changes are contained within the certification feature and do not impact other parts of the system. The workflow is cohesive, starting from the `CertificationList` page (which links to individual `CertificationDetail` pages) and allowing authorized users to navigate to the `CertificationCreate` and `CertificationEdit` pages. Validation and state management are robustly handled, minimizing potential side effects.

## ✅ Testing

> What testing have you done and verified? If you can't test, please say why that is.
> If testing is not possible, explain why and how it will be handled later (manual verification, etc.).
**Manual Testing has been conducted. ** 

## 🔗 References

> **Supporting Information**: Add relevant documentation, discussions, or background for this Pull Request.  
> This could include:
- Links to issue trackers (e.g., GitHub issues)
- API documentation
- External resources (StackOverflow, Notion pages, third-party package documentation)
**The dayjs package has been added for time keeping which is a great alternative for moment.js. But this might be removed if we do not require a library to handle the time as aspect strictly on this project.**
[dayjs](https://www.npmjs.com/package/dayjs)

2024-11-09 14:18 UTC, brooksideas commented on src/views/CertificationCreateForm.vue
> +
dayjs is already installed and will be used in integration task.

2024-11-09 14:29 UTC, brooksideas commented on src/views/CertificationEditForm.vue
> +  level: yup.string().required("Level is required"),
`duration: "02:30"` this is the format we expect it , so it is a correct to use a string.

2024-11-09 14:29 UTC, brooksideas commented on src/router/index.js
> +    name: 'certification-detail',
We are using snake-case for all route naming.

2024-11-09 14:37 UTC, brooksideas commented on src/views/CertificationCreateForm.vue
> +                {{ generalError }}
tailwind is handling it thus, it is not important to create a new central class.

2024-11-09 14:37 UTC, brooksideas commented on src/views/CertificationEditForm.vue
> +  level: yup.string().required("Level is required"),
fix here 
https://github.com/Ethiopian-Data-Science-Association/edsa-website/pull/11/commits/dde8b2fe0b619d45382512c3b81e43a2b0ae5860

2024-11-09 14:37 UTC, brooksideas commented on src/views/CertificationEditForm.vue
> +  rating: yup.number().min(1).max(5).required("Rating must be between 1 and 5"),
fix for this comment here.
https://github.com/Ethiopian-Data-Science-Association/edsa-website/pull/11/commits/dde8b2fe0b619d45382512c3b81e43a2b0ae5860

2024-11-09 15:12 UTC, LibenHailu requested changes
![image](https://github.com/user-attachments/assets/5818b703-fd95-4051-aacd-81f43871c0bd)

![image](https://github.com/user-attachments/assets/16f3e397-fbeb-4521-8e23-ba24afe7952b)


There is a contrast issue

2024-11-10 12:56 UTC, brooksideas commented
Here is the contract issue fixes. 

![image](https://github.com/user-attachments/assets/5b3f8944-f7cd-4120-8ae9-925d1ed30537)

![image](https://github.com/user-attachments/assets/cd52a935-75ec-4af9-a20a-85d34ed5fdbd)

![image](https://github.com/user-attachments/assets/0d3e3d47-a6fc-49dd-8ab3-f40a51b4d257)

2024-11-11 08:49 UTC, LibenHailu approved these changes

2024-11-12 11:50 UTC, merged